import localFont from "next/font/local";
import "./globals.css";
import Header from '@/app/Header/page'
import Theming from "@/Theme/Theming";
export const metadata = {
  title: "Tasvir-Ai",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <Theming>
        <Header/>
        {children}
       </Theming>
      </body>
    </html>
  );
}
